{% set name = "mieaa" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e701cbb6cc9586fe93dc686990ec8e96ca5f554296d0778cd2e5c3187278817f

build:
  number: 0
  noarch:
    python
  entry_points:
    - mieaa = mieaa.mieaa_cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - python >=3.5
    - requests >=2.19.1

test:
  imports:
    - mieaa
  commands:
    - mieaa --help

about:
  home: https://www.ccb.uni-saarland.de/mieaa2
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: miEAA Command Line Interface and API
  doc_url: https://mieaa.readthedocs.io/en/latest/
  dev_url: https://github.com/Xethic/miEAA-API

extra:
  recipe-maintainers:
    - jeffsolo
    - Xethic
